# Generated by Django 4.1.4 on 2022-12-11 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('FD', 'Feeding'), ('BP', 'Bath Products'), ('TY', 'Toys'), ('HS', 'Health & Safety'), ('SL', 'School Supplies'), ('DP', 'Diapering'), ('FW', 'Footwear'), ('GR', 'Gears'), ('GL', 'Girl Fashion'), ('BK', 'Books'), ('NS', 'Nursery Furniture'), ('BY', 'Boy Fashion')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andman & Nicobar Islands', 'Andman & Nicobar Islands'), ('Rajastan', 'Rajasthan'), ('Andra Pradesh', 'Andra Pradesh'), ('Kerala', 'Kerala'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Telangana', 'Telangana'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Punjab', 'Punjab'), ('Tamil Nadu', 'Tamil Nadu'), ('Bihar', 'Bihar'), ('Gujarat', 'Gujarat')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
