# Generated by Django 4.1.4 on 2022-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FW', 'Footwear'), ('BP', 'Bath Products'), ('BY', 'Boy Fashion'), ('FD', 'Feeding'), ('GL', 'Girl Fashion'), ('TY', 'Toys'), ('NS', 'Nursery Furniture'), ('SL', 'School Supplies'), ('BK', 'Books'), ('GR', 'Gears'), ('DP', 'Diapering'), ('HS', 'Health & Safety')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
