# Generated by Django 4.1.4 on 2022-12-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_user_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FD', 'Feeding'), ('GL', 'Girl Fashion'), ('BP', 'Bath Products'), ('BK', 'Books'), ('TY', 'Toys'), ('BY', 'Boy Fashion'), ('NS', 'Nursery Furniture'), ('SL', 'School Supplies'), ('GR', 'Gears'), ('DP', 'Diapering'), ('HS', 'Health & Safety'), ('FW', 'Footwear')], max_length=2),
        ),
    ]
