# Generated by Django 4.1.4 on 2022-12-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BP', 'Bath Products'), ('BY', 'Boy Fashion'), ('NS', 'Nursery Furniture'), ('GR', 'Gears'), ('DP', 'Diapering'), ('SL', 'School Supplies'), ('TY', 'Toys'), ('GL', 'Girl Fashion'), ('FD', 'Feeding'), ('FW', 'Footwear'), ('BK', 'Books'), ('HS', 'Health & Safety')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Telangana', 'Telangana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Tamil Nadu', 'Tamil Nadu'), ('Chattisgarh', 'Chattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Assam', 'Assam'), ('Andra Pradesh', 'Andra Pradesh'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Rajastan', 'Rajasthan'), ('Kerala', 'Kerala'), ('Andman & Nicobar Islands', 'Andman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Gujarat', 'Gujarat')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
