# Generated by Django 4.1.4 on 2022-12-16 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_product_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andman & Nicobar Islands', 'Andman & Nicobar Islands'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Telangana', 'Telangana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Tamil Nadu', 'Tamil Nadu'), ('Haryana', 'Haryana'), ('Kerala', 'Kerala'), ('Chattisgarh', 'Chattisgarh'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Chandigarh', 'Chandigarh'), ('Rajastan', 'Rajasthan'), ('Assam', 'Assam'), ('Andra Pradesh', 'Andra Pradesh'), ('Punjab', 'Punjab'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DP', 'Diapering'), ('FD', 'Feeding'), ('NS', 'Nursery Furniture'), ('GL', 'Girl Fashion'), ('BP', 'Bath Products'), ('SL', 'School Supplies'), ('BY', 'Boy Fashion'), ('TY', 'Toys'), ('BK', 'Books'), ('FW', 'Footwear'), ('GR', 'Gears'), ('HS', 'Health & Safety')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
