# Generated by Django 4.1.4 on 2023-01-16 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_customer_orderplaced_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Gujarat', 'Gujarat'), ('Tamil Nadu', 'Tamil Nadu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Telangana', 'Telangana'), ('Andra Pradesh', 'Andra Pradesh'), ('Rajastan', 'Rajasthan'), ('Kerala', 'Kerala'), ('Haryana', 'Haryana'), ('Chandigarh', 'Chandigarh'), ('Andman & Nicobar Islands', 'Andman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Delhi', 'Delhi'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BP', 'Bath Products'), ('TY', 'Toys'), ('NS', 'Nursery Furniture'), ('FW', 'Footwear'), ('HS', 'Health & Safety'), ('SL', 'School Supplies'), ('DP', 'Diapering'), ('BK', 'Books'), ('BY', 'Boy Fashion'), ('GR', 'Gears'), ('FD', 'Feeding'), ('GL', 'Girl Fashion')], max_length=2),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
